multinet-app/multimatrix

- src/css/adjMatrix/adj-matrix.css
- src/js/adjMatrix/controller.js
- src/js/adjMatrix/controller.ts
- src/js/adjMatrix/helper_functions.js
- src/js/adjMatrix/model.js
- src/js/adjMatrix/model.ts
- src/js/adjMatrix/view.js
- src/js/adjMatrix/view.ts
- src/js/loadTasks.js
- src/js/ui.js
Closes #8. 
This PR will contain a lot of changes to the way that highlighting currently works since there is a lot of code that differs from how we did it for the nodelink. It's best to try align on the strategy for highlighting.
> Allow highlighting from search box and from click

- src/css/adjMatrix/adj-matrix.css
- src/css/base.css
- src/index.html
- src/js/adjMatrix/controller.js
- src/js/adjMatrix/controller.ts
- src/js/adjMatrix/view.js
- src/js/adjMatrix/view.ts
Closes #11. 
The issues with rendering on chrome was a simple css problem. The width needed to be specified on the parent of the svg.
> Fix a typo in view and fix the css so that the svg renders on chrome

- src/js/adjMatrix/model.js
- src/js/adjMatrix/model.ts
- src/js/adjMatrix/view.js
- src/js/adjMatrix/view.ts
- src/js/multinet.js
- src/js/ui.js
Switch the labels to use _key instead of name since name won't be in each tables. Soon I'll add the ability to change the label to any variable.
> Update the matrix to work with any data in the database

- src/index.html
- src/js/adjMatrix/controller.js
- src/js/adjMatrix/controller.ts
- src/js/adjMatrix/view.js
- src/js/adjMatrix/view.ts
- src/js/loadTasks.js
- src/js/ui.js
Partial solution to #13. This will add the ability to change purely aesthetic things such as font size and which attributes are used for the label
> Add the label updating functionality to the config panel

- .github/workflows/main.yml
- README.md
- package.json
- src/__tests__/e-2-e.test.js
- src/__tests__/ui.test.js
- src/__tests__/utils.test.js
- src/js/loadTasks.js
- src/js/ui.js
- yarn.lock
Closes #7. 
Add some unit tests and an end to end test and the infrastructure to automate it.
> Add a test suite and continuous integration for the adjacency matrix view

- src/js/adjMatrix/model.js
- src/js/adjMatrix/model.ts
This removes all the pieces we don't need except the index variable name since that's used deeper in the application. Closes #22
> Fix the label options in the control panel

- src/__tests__/ui.test.js
- src/js/adjMatrix/controller.js
- src/js/adjMatrix/controller.ts
- src/js/adjMatrix/model.js
- src/js/adjMatrix/model.ts
- src/js/adjMatrix/view.js
- src/js/adjMatrix/view.ts
- src/js/loadTasks.js
- src/js/multinet.js
- src/js/ui.js
Add in sorting functionality. Closes #19
> Sorting and neighbor highlighting

- src/components/AdjMatrix/model.ts
- src/components/AdjMatrix/view.ts
> Make neighbor highlighting persist and fix individual cell highlighting

- src/App.vue
- src/components/AdjMatrix/AdjMatrix.vue
- src/components/AdjMatrix/controller.ts
- src/components/Controls.vue
Remove the old, unnecessary panel code, fix the menu overflow, and fix the svg sizing
> Add alignment fixes from nodelink

- src/components/AdjMatrix/controller.ts
- src/components/AdjMatrix/model.ts
- src/components/AdjMatrix/view.ts
- src/lib/provenance.ts
- src/lib/utils.ts
- tsconfig.json
First of a few iterative improvements for #33 
Must be closed after #35 and #34 (They're already merged)
Also fixes some loose ends found along the way
> Iterative improvement to typing and removal of some dead code

- .github/workflows/main.yml
> Add yarn caching to speed up CI builds

- src/App.vue
- src/components/AdjMatrix/AdjMatrix.vue
> Fix css scoping

- src/components/AdjMatrix/AdjMatrix.vue
- src/components/AdjMatrix/model.ts
- src/components/AdjMatrix/view.ts
- src/components/Controls.vue
> Implement the attributes view into the adjacency matrix

- src/components/Controls.vue
This is preventing CI-based build.
> Fix typescript warning/error

- src/components/AdjMatrix/AdjMatrixMethods.ts
> Add color encoding to cells

- public/index.html
> Update the html title

- src/components/AdjMatrix/AdjMatrix.vue
- src/components/AdjMatrix/AdjMatrixMethods.ts
- src/components/Controls.vue
- src/lib/multinet.ts
- src/lib/utils.ts
Closes #58
Closes #61
This will currently break the deployment since the query string parameter is graph, not network. 
Opened multinet-app/multinet-client#90 to switch from graph in the querystring to network
> Update naming conventions to match project naming conventions

- src/components/AdjMatrix/AdjMatrix.vue
- src/components/AdjMatrix/AdjMatrixMethods.ts
- src/components/Controls.vue
- src/lib/multinet.ts
- src/types.ts
Fixes a lot of minor issues:
- Tooltip positioning
- D3 does not plot outside the SVG (I think this was causing #37 so this closes #37)
- Adds better typing (closes #33)
- Refactors the hovering logic
Partial fix for #59.
These fixes simplify some of the hovering logic which will be important for debugging the slow highlighting
> Lots of minor fixes

- package.json
- src/lib/multinet.ts
- yarn.lock
Also fixed the string interpolation in this file
> Send credentials on requests to api

- README.md
> Update README to describe the application

- src/components/AdjMatrix/AdjMatrix.vue
- src/components/AdjMatrix/AdjMatrixMethods.ts
Fixed everything in the fix labels branch before the highlight broke and the rendering problems did not work. 
The changes made were all of the changes requested in the fixed-labels PR request which I have reopened. The code in that request is broken so this is the code that needs to be reviewed. The issue that hasn't been fixed (which I am still having problems with) is resizing the svgs without the highlights crashing and having the svg work for any size network data.
> Fixing labels revision1

- package.json
- src/components/Controls.vue
- src/lib/multinet.ts
- yarn.lock
Mostly reverts #104 , and bumps multinetjs version.
> Revert use of login tokens for auth, use cookies

- src/lib/aggregation.ts
Closes #123
This PR addresses the any type issue in aggregation.ts.
> Fix Any Type in Aggregation.ts

- src/components/Controls.vue
A couple small fixes. The title says it all 😄
> Fix capitalization and chip size in the control panel

- src/components/MultiMatrix/MultiMatrix.vue
Close #184 
Close #185 
Close #193
> Indent Child Node Row Labels and Create Visual Identifier for Child Node Row and Column Labels

- src/components/Controls.vue
- src/components/MultiMatrix/MultiMatrix.vue
- src/lib/aggregation.ts
- src/types.ts
This PR builds off PR #192 
Close #186
Close #187 
Close #189 
Close #174 
Close #195
Close #80 
Demo
https://user-images.githubusercontent.com/24800816/107292195-4a1e6080-6a1e-11eb-8bc9-e3815d44b5c7.mp4
> Hierarchy (Cell Colors and Legends)

- src/lib/aggregation.ts
This PR fixes bugs that appear in the les mis data that are not visible in the small flight dataset.
Fixed Node Ordering for Aggregating by Group for Les Mis
Close #210 
Close #201 
Close #128 
Close #80 
Opened the following issues for this PR
Open #213 
Open #212 
Open #211 
Demonstration of Changes
https://user-images.githubusercontent.com/24800816/109598833-f360ef80-7ace-11eb-92f0-66697f649ecc.mp4
> Fix Aggregation For Visualizing Large Data

- src/components/MultiMatrix/MultiMatrix.vue
- src/lib/aggregation.ts
This PR adds icons for the expand/retract matrix view when the network is aggregated on a single attribute. 
The following issues were addressed:
Close #211 
Close #201 
Close #218 
Issues associated with this PR:
https://github.com/multinet-app/multimatrix/issues/218 
https://github.com/multinet-app/multimatrix/issues/212
https://github.com/multinet-app/multimatrix/issues/213
#223 
#224
> Aggregation UI Buttons

- src/components/MultiMatrix/MultiMatrix.vue
- src/lib/aggregation.ts
https://user-images.githubusercontent.com/24800816/114766208-f92b3100-9d1a-11eb-81aa-9fbc152ba34b.mp4
Child Label
> Add labels for keeping track of the number of children that belong to a supernode

- src/components/MultiMatrix/MultiMatrix.vue
Closes #165
Add the simulation link logic from the MultiLink application (with the addition of using find() to get the nodes, not just the strings)
> Use a computed prop for the reorderjs links

- src/App.vue
- src/components/Alert.vue
- src/components/Controls.vue
- src/components/MultiMatrix/MultiMatrix.vue
- src/store/index.ts
- src/types.ts
Closes #221
Closes #220
Refactors a lot of logic that handled data binding and event emitting between the controls and the matrix component. That logic now lives in the store.
Once side effect of this change is that we can now move the matrix component out of the controls, so they're easier to maintain. 
TODO:
> Prefer using the store over data binding and emits

- package.json
- public/index.html
- src/App.vue
- src/components/Controls.vue
- src/components/LineUp.vue
- src/components/ProvVis.vue
- src/lib/provenanceUtils.ts
- src/store/index.ts
- src/types.ts
- yarn.lock
Adds trrack and trrack-vis. To keep things simple, I copied a ton of the configuration and logic from the multilink application.
I started by just tracking `selectNeighbors`, since that's a very easy way to verify that the provenance functionality is working. You can see from the vis (and the control toggle) that navigating around the trrack-vis works and that the vuex state is being updated as the provenance is updated (and vice-versa).
TODO:
> Add trrack and trrack-vis

- src/components/Controls.vue
- src/components/MultiMatrix.vue
- src/lib/provenanceUtils.ts
- src/store/index.ts
- src/types.ts
Closes #271
Adds several variables to trrack:
- grid lines
- directional edges
- aggregation
- selects and de-selects
> Add (de-)select nodes and cells to provenance

- src/components/ConnectivityQuery.vue
- src/components/Controls.vue
- src/components/FilterOverlay.vue
- src/components/LineUp.vue
- src/components/MultiMatrix.vue
- src/store/index.ts
- src/types.ts
At the moment there is no functionality and the UI is ugly.
I wanted to get some initial feedback from @JackWilb about whether I set the component up correctly (I didn't use composition API).
> Connectivity query

- src/components/Controls.vue
Closes #198
Remove the append call inside updateLegend so we don't keep adding a ton of g elements each time the matrix updates
> Don't append a g each time updateLegend is called

- src/components/MultiMatrix.vue
> Re-enable no-explicit-any

- src/components/AboutDialog.vue
- src/components/Controls.vue
- src/components/FilterOverlay.vue
- src/components/LoginMenu.vue
- src/components/MultiMatrix.vue
- src/components/ProvVis.vue
Depends on #308 ~~(will need one additional change in controls.vue since this branch missing a commit that adds a watcher)~~
Closes #247
Converts the remaining options API over to composition. It didn't require too much work, but we could improve this by grouping together relevant code so it's not so spread out, especially in MultiMatrix.vue
> Convert all components to composition API

- src/components/MultiMatrix.vue
- src/store/index.ts
- src/types.ts
I noticed some of the watchers weren't firing as we expected and that the nodes weren't expanding from the right spot
> Clean up some composition API conversion issues

- src/components/ConnectivityQuery.vue
- src/components/Controls.vue
Focused on readability and some UX
Super open to suggestions!
> Make query pretty

- src/components/ConnectivityQuery.vue
- src/components/IntermediaryNodes.vue
- src/components/MultiMatrix.vue
- src/components/PathTable.vue
- src/store/index.ts
- src/types.ts
There are a few things left to do:
> Display path table

- src/components/LoginMenu.vue
> Redirect to multinet.app on logout

- src/components/Controls.vue
- src/components/MultiMatrix.vue
- src/store/index.ts
This adds ability to change cell size from the control panel and resizes all the relevant pieces of the matrix.
I also took the opportunity to clean up some of the parameters here and just make it a bit easier to deal with.
This doesn't work for the lineup view, yet. We should open an issue to deal with that.
> Add cellSize slider and logic to handle resize

- src/components/PathTable.vue
Instead on choosing only one column header, users can now pick multiple column headers in the path table
> Add dynamic columns to table

- src/components/ConnectivityQuery.vue
- src/components/MultiMatrix.vue
- src/components/PathTable.vue
- src/lib/provenanceUtils.ts
- src/store/index.ts
- src/types.ts
With this update, you should be able to click the matrix (after a 1-hop query) and it will display a path table with the paths.
Closes #334
> Path table update

- package.json
No
Runs the linter in production mode to catch console.logs
N/A
No
> Make the linter run in production mode

- yarn.lock
Updates all packages that need a patch upgrade (e.g. 1.0.0 to 1.0.3). I didn't touch major and minor versions here because that was throwing errors for me locally
> Update all patch updates and security updates

- src/components/Controls.vue
- src/components/IntermediaryNodes.vue
- src/components/PathTable.vue
- src/store/index.ts
- src/types.ts
Closes #352 
This addition allows the user to aggregate the intermediate node table by node variable.
TODOs:
> Intermedia node aggregation

- src/components/Controls.vue
- src/components/LineUp.vue
- src/components/MultiMatrix.vue
- src/lib/provenanceUtils.ts
- src/store/index.ts
- src/types.ts
Closes #365
This is all under the hood changes and shouldn't have an effect on the UI. Apparently the selected nodes were already tracked in the store so I changed the variable tracking them to a set, since they should be unique.
Additionally, I added some helper functions that are used in multilink to help speed up some of my future work. This will mean I can copy some code over verbatim to clear the selection, etc.
No behavior changes expected.
No
> Selected nodes in store

- src/components/ConnectivityQuery.vue
No
There were a couple of warnings that weren't being captured by linting/building. I've resolved them here.
No
> Fix connectivity query bugs

- package.json
- src/components/ConnectivityQuery.vue
- src/components/Controls.vue
- src/components/FilterOverlay.vue
- src/components/MultiMatrix.vue
- src/lib/utils.ts
- src/store/index.ts
- src/types.ts
- yarn.lock
Closes #386 
Let's the user filter nodes based on the number of out degrees.
I'm sure the code will need some sprucing up. I'm not sure I computed the filtering in the best way.
TODOs:
> Calc degrees

- yarn.lock
Closes dependabot number 56
Bumps thenify
N/A
No
> Bump thenify to 3.3.1

- src/components/ControlPanel.vue
No
Created a method for exporting the network as a CSV. Treats the network as a 1-hop path between nodes.
TODOs:
> Create CSV exporter

- .eslintrc.js
- src/components/FilterOverlay.vue
- src/components/IntermediaryNodes.vue
- src/components/PathTable.vue
- src/lib/provenanceUtils.ts
- src/lib/utils.ts
- src/store/index.ts
No
The title explains it well. The main thing I changed was to allow parameter reassignments for props.
N/A
> Modify some eslint rules and refactor some code that required disabling of rules

- package.json
- src/components/ConnectivityQuery.vue
- src/components/FilterOverlay.vue
- yarn.lock
No
There is an upstream change to the way we should be submitting AQL queries. To fix this, we needed to update the multinetjs library
N/A
No
> Update multinetjs to align with upstream changes

- package.json
- yarn.lock
Fixes aql bind vars in the query for network subsetter
N/A
No
> Bump multinet-components to 0.0.4

- .eslintrc.js
- src/components/AlertBanner.vue
- src/components/ConnectivityQuery.vue
- src/components/ControlPanel.vue
- src/components/MultiMatrix.vue
- src/lib/utils.ts
- src/store/index.ts
- src/store/provenance.ts
- src/types.ts
- yarn.lock
Closes #
Fixes the network computation and setting issues when modifying the network from the alert banner, connectivity query, slicing, etc.
N/A
TODOs:
> Fix network computation

- src/main.ts
No
This better handles the local storage, cookies, and their invalidation. 
N/A
TODOs:
> Fix issues with invalidating cookies and restoring logins

- src/components/MultiMatrix.vue
- src/lib/provenanceUtils.ts
- src/store/index.ts
- src/store/provenance.ts
- src/types.ts
- yarn.lock
Closes #458 
This makes the labels for trrack more descriptive. I also took the time to fix a bug with expanding and retracting nodes.
N/A
No
> Trrack labels

- src/components/ControlPanel.vue
- src/store/index.ts
No
This sort option shows the neighborhoods so I renamed the option in the menu
N/A
No
> Rename RCM to neighborhoods

- src/components/ProvVis.vue
> Fix trrack type issues

- components.d.ts
- index.html
- src/App.vue
- src/components/AlertBanner.vue
- src/components/ColorScaleLegend.vue
- src/components/ConnectivityQuery.vue
- src/components/ControlPanel.vue
- src/components/EdgeSlicing.vue
- src/components/LineUp.vue
- src/components/MultiMatrix.vue
Closes #425 
This PR adds the new sidebar styling with the accordion expansion panels and fixes the scrolling issues that existed with the matrix.
https://github.com/multinet-app/multimatrix/assets/36867477/65159e36-4c20-4d2d-a278-53f9109623e3
No
> Fix sidebar styling and matrix scrolling issues

- src/components/MultiMatrix.vue
Closes #442
There were 2 issues with the tooltip, text wrapping and some keys that needed to be hidden. I've addressed them both here. I'll propagate these changes to multilink
Before is in the issues.
After:
No
> Fix some minor issues with the tooltip
