multinet-app/multimatrix

- src/components/AdjMatrix/AdjMatrix.vue
- src/components/AdjMatrix/AdjMatrixMethods.ts
Depends on #63 
There are a couple of ideas we had to reduce the hover rendering slowness:
Tried and in the PR:
- Reducing the number of DOM elements (> 10,000 from the cell rendering logic on the miserables graph)
Proposed solutions:
These were not tested since reducing the number of elements seems to have fixed the problem.
> Fix hover rendering slowness

- src/components/AdjMatrix/AdjMatrix.vue
- src/components/AdjMatrix/AdjMatrixMethods.ts
Depends on #64.
Adds styling back to the tooltip that was partially recovered in #64.
TODO:
> Show node and link data on hover

- src/components/AdjMatrix/AdjMatrixMethods.ts
Tasks Completed (currently works for les mis and flight datasets)
- resized the cells to 11 x 11 
- resized grid for the new cells
- reshaped cells to have round corners
- fixed the row and column highlights to work with the new cell and grid size
Things that might need fixing
- resizing the labels (don't know if they are too big with the new layout)
> Revised grid layout

- public/index.html
- src/App.vue
Closes #90.
Adds the Blinker font from Google Fonts, as specified by @jtomeck. I also fixed the import of roboto to use the new `css2` endpoint from google
> Add Blinker font as the main font for the app

- src/components/AdjMatrix/AdjMatrix.vue
- src/components/AdjMatrix/AdjMatrixMethods.ts
This prototype is a solution for how to handle the label cutoff problem with SVG text using SVG Foreign Objects.
This is a picture with the foreign objects for the rows 
currently working on foreign objects for columns
> Implement ellipsis for long label cutoff for the adjacency matrix

- src/components/AdjMatrix/AdjMatrix.vue
- src/components/Controls.vue
This branch creates the grid toggle for showing/hiding the grid lines for the matrix.
The following images displays different kinds of toggles for showing/hiding the gridlines. The toggle selected was the checkbox because it easy to understand how to use and connects well with the adjacency matrix.
> Implement Grid Toggle for Showing/Hiding Matrix Gridlines

- src/components/Controls.vue
After #102, which uses a checkbox instead of a switch, the remaining switch in the UI feels out of place, and a checkbox seems like the better choice.
This tiny PR changes that switch to a checkbox.
> Change the lone v-switch to a v-checkbox

- package.json
- src/components/Controls.vue
- src/lib/multinet.ts
- yarn.lock
Adds a method to grab the login token from the query string so that a user can view data from private workspaces. This function is slightly different to that created by @AlmightyYakob, since we're not using vue router on this project, and the api is only handled in one spot on first load -- it's not continually accessed, unlike the main client.
> Add authentication token receiving from the querystring

- src/components/AdjMatrix/AdjMatrix.vue
- src/components/AdjMatrix/AdjMatrixMethods.ts
- src/components/Controls.vue
Adds a stop-gap solution to update the network object in the vue component from a change in the matrix ts class. This will need to be backed out when we do the re-architecting.
It might make sense to make an issue to track backing this logic out
> Add eventBus to emit and catch network update from the class object to the vue component

- src/components/AdjMatrix/AdjMatrix.vue
- src/components/AdjMatrix/AdjMatrixMethods.ts
- src/components/Controls.vue
Depends on #120.
Adds a boolean flag to enable/disable the superGraph creation, and some UI to manage the toggling. Currently, this code just disables the attribute column header selection, since @mozartfish told me that the "Aggregate California" button will be removed before he merges #120. This should disable any call to `superGraph()`, thus disabling the graffinity features
Leaving as a draft for now, until @mozartfish merges #120.
Closes https://github.com/orgs/multinet-app/projects/6#card-48781425
> Allow disabling and enabling of graffinity aggregation features

- src/components/MultiMatrix/MultiMatrix.vue
- src/components/MultiMatrix/MultiMatrixMethods.ts
Relates to #141 
This is the first of many changes to remove the class logic and moves the `processData` function out of the class. To do this, I needed to set up a few `data` variables in the vue component and move the logic. Since some of the variables (`idMap` and `matrix`) need to be regenerated when the network changes, I separated some of the logic out into functions. That lets me call them in multiple places, e.g. on mount and when the matrix updates for graffinity aggregation.
I also tried to simplify some logic where I saw fit by moving the class variable instantiation out of the constructor, and removing matrix node length.
> Move processData and some helpers to MultiLink.vue

- src/components/MultiMatrix/MultiMatrix.vue
- src/components/MultiMatrix/MultiMatrixMethods.ts
Another step towards #141 
This moves the initialize attributes function to MultiMatrix.vue.
I had to duplicate some logic: `showTooltip`, `hideTooltip`, `isCell`, `capitalizeFirstLetter`, `hoverNode`, `unHoverNode`. The best strategy (that I could think of) was to duplicate the logic, since the code is used in both `initializeAtrributes` and `initializeEdges`. I'll remove the duplicated code when the `initializeEdges` is moved.
I also commented out the code for on click for the attribute rows to reduce the amount of duplicated code. I'll also re-enable that once I move `initializeEdges`.
This introduces a new bug that I'll have to track down. Sorting a aggregated network causes there to be a bunch of blank rows. I would guess that it's to do with how the network is being updated. I'll …
> Migrate initializeAttributes to MultiMatrix

- src/components/Controls.vue
- src/components/MultiMatrix/MultiMatrix.vue
Closes #145 
Prior to this PR, edges were being counted in both directions. This is fine when that information is not directional (like a relationship in the les mis dataset), but when the edges encode a specific directional relationship we want to see that. This PR addresses that issue.
I added a toggle for edge directionality and updated the code to only count in one direction if directional edges is on. This code required a bit of duplicated logic for watching the `directional` prop and updating the matrix. Once we have a better strategy for handling updates to props (enter, exit, merge, etc.) we can refactor this so that we don't need to tear the matrix down and rebuild it.
> Add toggle to enable edge directionality

- src/components/MultiMatrix/MultiMatrix.vue
Depends on #160 (That uses the generateIdMap function, so I figured it would be easier to remove it in this follow up)
Closes #143 
I altered the logic for generating the idMap, by turning it into a computed prop. The idMap is generated from this.network so when the network changes, so does the idMap. 
I saw room for a secondary improvement, which was removing the `index` property from the nodes, since that is calculated in the idMap step and is superflous. The index of the nodes in this.network will not change after this.idMap is generated, which it is every time the network updates.
> Make idMap a computed property, instead of a data prop

- src/components/MultiMatrix/MultiMatrix.vue
- src/lib/aggregation.ts
- src/lib/multinet.ts
- src/types.ts
Depends on #160 (Since the logic for calculating the cell fill is based on source & target)
Closes #144 
I removed all references to source and target from the app, instead preferring to use _from and _to. This simplifies the logic in data pulling and in aggregation, and keeps it about the same elsewhere. There is one spot that required source and target, the sorting using reorder.js, so there is a spot where source and target are generated as they are needed. The logic to do that already existed, though.
> Prefer _from and _to to source and target

- src/components/MultiMatrix/MultiMatrix.vue
Might address #150 (will need to be tested with a network that will add and remove nodes in place)
Closes #148 
Adds D3 style enter, exit, merge to the rendering function and stops the matrix from being fully removed during each re-render. I also moved some of the icon rendering logic since that doesn't need to be re-rendered on each network update.
Open questions:
- Where should we move the gridlines to? I can see a place for them inside the matrix rows and in the vue rendering. We could also remove them
- Should I try move some of the rendering to the vue layer or do we need D3 for transitions etc.?
- I think I used an old syntax, would it be worth trying to update it to use D3v5 joins instead?
TODO (these can likely just become issues for follow ups):
> Add D3 enter, exit, merge to allow the network to be changed in place while triggering a re-render of the matrix

- src/components/MultiMatrix/MultiMatrix.vue
Closes #170
There were a couple issue that needed to be fixed in this PR:
1. The color scale could never reduce its max value, since the max value was never reset
2. Updates to the colorScale didn't automatically trigger an emit, it was a separate event. Using a watcher for this would solve the problem.
3. The code was a little dispersed and could be condensed into a computed prop
I fixed the 3 issues above using the solutions that I mentioned, resetting the max value, using a watcher instead of manually emitting changes to the color scale, and making the colorScale a computed prop.
> Fix color scale legend calculation and legend reactivity

- src/components/MultiMatrix/MultiMatrix.vue
This doesn't address a specific issue
The matrix was not resizing and since we're adding and removing rows, that's become an issue. This moves the resizing code from the `mounted()` function to the template so that the size is reactive to changing numbers of nodes. I also migrated the sizing for the attributes panel so now they should all stay in sync
> Move the matrix sizing to the template

- src/components/MultiMatrix/MultiMatrix.vue
Closes #171
The code that renders the cells was not able to update existing DOM elements with new fill and with new position (e.g. @mozartfish updates). This fix solves that problem by defining the fill and position on the new elements. To do that, I need to add a component level data variable to track the cells (this.cells) and then call the updates on that.
> Make the cells reactive to updates from prop

- src/components/MultiMatrix/MultiMatrix.vue
This doesn't address a specific issue, but does seem to fix #168 as a by-product
I copied the same formula from the reactivity of the cells for this and made the attributes reactive. I changed the logic slightly so now it's not done by row, it's instead done as columns, one for each variable, which helps reduce complexity when defining width, x, etc. The zebras and highlights are now much better, too, and they react as you'd expect
Appologies in advance for the large commit 24ed92b, it's a bit of a monster since it was hard to break out the code moving from the logic changes.
> Make the attribute vis reactive to changes

- src/components/MultiMatrix/MultiMatrix.vue
- src/lib/aggregation.ts
Closes #124
Close #132 
Closes #115 
PR for restructuring the expand supernodes so that the matrix will not re-render every time the user clicks on a chevron
Demo Video
https://user-images.githubusercontent.com/24800816/104494774-bf1b8900-558b-11eb-9075-1715f0471540.mp4
> Restructured expand supernodes

- src/components/MultiMatrix/MultiMatrix.vue
- src/lib/aggregation.ts
Close #181 
Adds index tracking code to allow for children nodes to drop down from their parent node positions. Exit Transition was not fixed in this PR because of some timing issue with Vue. For column labels, a fade transition was added as well to animate the columns.
> Animating Rows - Fixes Issue #181

- src/components/MultiMatrix/MultiMatrix.vue
Close #197 
This commit fixes a bug for the attribute table. The bug grouped all the aggregate nodes into a single category when the matrix was grouped in a supernode such as in this image from the multimatrix.app page 
The fix is demonstrated below
https://user-images.githubusercontent.com/24800816/107675699-3147c200-6c4d-11eb-8ae1-a4192f819af0.mp4
Remaining issue is #200
> Table attributes

- src/lib/multinet.ts
Closes #204
Bumps the download limit for a node table to 300 nodes. This make the app work with the boston dataset, again.
> Allow for a larger node table (upto 300 nodes per table)

- src/components/MultiMatrix/MultiMatrix.vue
Closes #166
Moves the tooltip 256 pixels left, the width of the sidebar. The variable I'm using to track this could eventually end up in the vuex store, similar to how it is on the MultiLink application.
> Fix tooltip x positioning by subracting the sidebar width

- src/components/MultiMatrix/MultiMatrix.vue
This PR implements restoring the matrix to its original non-aggregated state when the user toggles the enable graffinity features to the left. This PR builds upon the following PR and its associated issues: Aggregation UI Buttons
Close #164 
Demo 
https://user-images.githubusercontent.com/24800816/112214935-02722380-8bdd-11eb-9fb6-a2b0ddcfcad2.mp4
> Restore Matrix

- netlify.toml
There's an extra /api on the live server. This problem was from netlify.toml
> Fix api route in netlify.toml

- src/components/MultiMatrix/MultiMatrix.vue
Closes #91
Small fix to enable the controls toggle to work. When toggled off, don't highlight neighbors at all (also removes all neighbors on another select).
> Fix auto select neighbor toggle

- src/App.vue
Closes #251
Adds a v-if to only show the matrix once the network has loaded and is not null. This fixes the banner issue that was referenced in #251
> Mount matrix when the network is available

- src/components/LineUp.vue
Closes #267
The crash was caused by a duplicated index value being included in the selection array. I fixed it by converting to set and back before passing the array to the lineup
> Make sure indices are unique before setting selection in lineup

- src/components/LineUp.vue
- src/components/MultiMatrix.vue
- src/lib/aggregation.ts
- src/lib/utils.ts
- src/store/index.ts
- src/types.ts
Closes #266
To be more consistent across the code, I renamed all instance of link to edge (pending a test of the aggregation since we can't trigger it at the moment)
I also fixed the hover highlight by removing all highlighted rows when the mouse leaves the lineup component
> Rename link to edge and fix mouseout selection in lineup

- src/components/ConnectivityQuery.vue
> Make aql query more robust

- src/components/ConnectivityQuery.vue
This change simplifies the logic of the connectivity query component by removing the arrays that existed for each specific type (nodes and edges), replacing them with one list that controls both. This change affects all instances of there being two lists performing the same function.
In so doing, this simplifies the `queryOperator` logic and allows for path filtering with the operators (currently `==` and `=~`).
Another nice thing this change gives us is a more condensed html template, since we can reuse the same arrays everywhere
> Simplify connectivity query component

- src/components/ConnectivityQuery.vue
- src/components/FilterOverlay.vue
- src/store/index.ts
- src/types.ts
Closes #281 
This change will make it possible to switch between queries without refreshing the page.
It will also show all possible options for large networks because it will pull the values from the original network.
> Move network variables to store

- src/components/MultiMatrix.vue
Closes #289
I fixed the logic that sets the location for the tooltip, reordered the events so that the cell event is not overwritten by a row event, and added a z-index so it doesn't get hidden by lineup. The end result is that the location is now consistent, the cell hovering now shows the right message, and the tooltip doesn't get hidden by lineup elements.
> Update tooltip logic so that position is consistent + show cell message

- src/components/Controls.vue
- src/components/MultiMatrix.vue
- src/store/index.ts
- src/types.ts
Closes #290
I chose to use one scale for all "normal" nodes and one for super nodes. This means that lots of the child node logic can be removed and simplifies the code quite a bit. 
To keep the child legend, I used a ternary operatore to show/hide the legend and to change the name of the legend.
> Remove all child node logic, child nodes are now "normal" nodes

- src/components/MultiMatrix.vue
Closes #295
Moves the `processData` call into `initalizeEdges`  since we always want the data to be fresh when we call `initalizeEdges`
> Move processData call into initializeEdges

- src/components/Controls.vue
Closes #65
This change means that the downloaded network can be re-uploaded to the multinet instance.
> Return a d3 json style network from export network

- src/components/ConnectivityQuery.vue
- src/lib/typeUtils.ts
- src/store/index.ts
- src/types.ts
Closes #241
I adopted the logic from MultiLink to filter out internal variables from the list of node variables and link variables. Since the node variables are tracked in the store, it was a simple fix. The link variables also only appear in one spot
> Remove internal/arango vars

- src/components/MultiMatrix.vue
Closes #92
Using Roni's/Jared's suggestions and [this article](https://ux.stackexchange.com/questions/53791/avoiding-the-hermann-grid-illusion) I've attempted to fix this problem.
I removed the border radius on the cells and darkened the grid lines. It seems to remove the effect for me, but I'd like a quick sanity check that it works on other machines.
> Alleviate grid illusion by removing cell radius and darkening lines

- src/components/ConnectivityQuery.vue
- src/components/Controls.vue
- src/lib/provenanceUtils.ts
- src/store/index.ts
- src/types.ts
Closes #291
Replace the enable aggregation switch and drop down with a single v-autocomplete that handles it all. The default is `'none'`. This provides a slightly better UX since a user can now switch between variables without disabling the aggregation first, and there are less click in general.
> Replace aggregation UI with a single v-autocomplete

- src/components/AboutDialog.vue
- src/components/Alert.vue
- src/components/ConnectivityQuery.vue
- src/components/Controls.vue
- src/components/FilterOverlay.vue
- src/components/IntermediaryNodes.vue
- src/components/LineUp.vue
- src/components/LoginMenu.vue
- src/components/MultiMatrix.vue
- src/components/ProvVis.vue
This is an improvement that I found doing some work on MultiLink (with the help of Roni and Jake). We need to use `defineComponent` when using props (which we're not), but it's probably just best to use it all the time. This means that if we want to use a new feature, we'll likely get the typescript support through this function
> Use defineComponent in each component

- src/components/MultiMatrix.vue
After my recent changes to the composition API, I noticed that the cells weren't able to be selected. This code fixes that issue
> Fix the selected cells watcher

- src/components/IntermediaryNodes.vue
Closes #311
Removing the visual elements and redrawing is the fastest path to what we want. We should check that we're not missing any data because of a weird enter/exit issue.
Let me know what you think @gotdairyya. We could also try to approach this in a smarter way, using ids and the proper d3 enter exit merge, but it might be more work than it's worth
> Add function to throw out old visual before re-rendering int node vis

- package.json
This will make the `yarn lint` command function the same way it does on multilink and the client. 
A byproduct of this change is that it will be harder to commit code that doens't pass the linter's validation. This could cause some more work when coding, but it will mean that it won't need to be tidied up on PR review.
You can always bypass this with `git commit -m "message" --no-verify` if we're going to defer the work until the review is over
> Make the linter fail on warnings

- src/components/MultiMatrix.vue
Closes #325
Allows the lablels to resize dynamically with cellSize. I moved the font-size controls into the d3 code and updated the margins to allow for the larger dynamic labels.
Original behavior for a large cellSize:
New behavior for a small cellSize:
New behavior for a large cellSize:
> Refactor label font-size and margin-top to allow label resizing

- src/components/LineUp.vue
Closes #323
This PR adds a watcher for cellSize in the lineup component that redraws the whole lineup componenet. This comes with significant performance issues.
My goal is to explore lineup's documentation + implementation to see if it's possible to update the `rowHeight` parameter without a full re-render.
> Make lineup re-render to adjust rowHeight based on cellSize

- src/components/IntermediaryNodes.vue
- src/components/LineUp.vue
- src/components/MultiMatrix.vue
Closes #324
I refactored some of this logic to work with the changing cellSize. In so doing, I've simplified the logic slightly using translates where possible to remove the number of positioning steps. 
The new set up is 1 cell width for labels, 0.5 cell width of padding either side of the cells and then 1 cell width for each row of cells. This seems to work pretty well at the moment. We'll need to do some testing to make sure this generalizes well
I haven't been able to test this with the full size since the matrix becomes too large for my screen
New behavior for small cell size:
New behavior for large cell size:
TODO:
> Make int nodes table reactive to cell size

- .github/workflows/main.yml
Nope, it's just an improvement to help us reduce redundant code across the repos.
I've added an action in multinet-app/.github that handles this logic. The gameplan is to prefer using that to workflow files in each individual repo to provide more consistent testing.
N/A
TODOs:
> Use the generalized linting workflow from the org .github repo

- src/components/ConnectivityQuery.vue
Closes #284
Adds `!=, <, <=, >, >=` query operators and allows them to work with numeric data types in arango. I explicityly cast `TO_NUMBER` when we're using a greater than or less than.
Please test and let me know what I broke. I did some minimal testing locally without any issue, though
> Add additional query operators

- src/components/Controls.vue
- src/components/MultiMatrix.vue
- src/lib/provenanceUtils.ts
- src/store/index.ts
- src/types.ts
No. We hadn't opened one for it
Add the ability to toggle the label variable between any of the node attributes. If no label is selected, the `_key` is shown
Without a variable selected:
With a variable selected:
TODO:
> Allow label update

- src/components/LineUp.vue
Depends on #356 
Closes #358
This PR hides internal variables from lineup. I added back `_key`, since it's the default label variable, and I didn't want it to be confusing
Here's what remains on the les mis data set:
No
> Remove internal columns from lineup, except _key

- src/components/ConnectivityQuery.vue
- src/components/Controls.vue
- src/components/IntermediaryNodes.vue
- src/components/MultiMatrix.vue
- src/store/index.ts
- src/types.ts
Closes #357
Refactors the control menu to look more like multilink with the expanding card. I decided to simplify it down to one card, unlike on multilink, since Alex has been telling me that there isn't a clear reason why it's split up. 
On my path to this design, I also fixed some other issues:
- The legend SVGs were too large and overlapped with the `v-autocompletes`
- I made it so that the `aggregatedBy` could be cleared, allowing the resetting of the labels.
- I grouped controls that had visual styles together
Previous look:
Current collapsed look:
Current expanded look:
TODO:
> Redesign the control panel to more closely match multilink

- src/components/LineUp.vue
No
Simply collapses the popover side panel on first load. See images below for the change.
Uses [this method](https://lineup.js.org/master/docs/classes/_builder_databuilder_.databuilder.html#sidepanel) from lineup.
Previous behavior:
New behavior:
No
> Collapse side panel on lineup first load

- src/components/Controls.vue
Closes #363 
I re-implemented node searching, using similar UI and functions to those that exist in multilink. This new search bar acts as if you're clicking. That is, if the node is unselected it will be selected, and if it's selected it will be unselected. This might not be ideal, but to change it would require a rewrite of quite a bit of code. Let me know how the UX is. The search also works within aggregated nodes.
I didn't test with any intermediary nodes, so that might be broken.
I also adjusted some margins that weren't needed after this change
New search bar:
TODOs:
> Re-implement node searching

- src/components/ContextMenu.vue
- src/components/MultiMatrix.vue
- src/lib/provenanceUtils.ts
- src/store/index.ts
- src/types.ts
Depends on #366 
No
This adds a context menu when right clicking on the matrix that will clear the selected nodes. 
Context menu:
No
> Add context menu to clear the selected nodes

- src/components/Alert.vue
- src/components/ConnectivityQuery.vue
- src/components/Controls.vue
- src/components/FilterOverlay.vue
- src/components/MultiMatrix.vue
- src/store/index.ts
- src/types.ts
Closes #360 (thanks @gotdairyya)
Closes #376
This PR restricts the columns we can aggregate by if we have type information from the API. If the type data is null, it will show all columns as before.
N/A
TODOs:
> Only allow aggregating by category if column types are available

- src/components/ConnectivityQuery.vue
- src/components/Controls.vue
Closes #375
I made this fix in an attempt to fix something else that didn't need this. Since I had the code already, I figured I should submit it for PR. 
The changes are simple. This PR just makes the connectivity query start collapsed and be expandable with the chevron as our other menu items are
Before:
Now:
No
> Start connectivity query collapsed, allow expansion with chevron

- src/components/ConnectivityQuery.vue
- src/components/Controls.vue
Closes #335 
Closes #282 
This PR will make it so that a user can conduct advanced querying of the connectivity network.
At the moment we can only query for one attribute per node or edge, and we'd like to query for more than one attribute.
TODOs:
> Make querying more robust

- src/components/LineUp.vue
- src/components/MultiMatrix.vue
Depends on #391 
Closes #259
Closes #260 
Fixes matrix sorting. You can now sort by node, cluster, etc.
TODOs:
> Fix sorting

- src/components/LineUp.vue
- src/components/MultiMatrix.vue
Closes #401 
Closes #397
Closes #263 (no more crashing)
This PR addresses a couple of issue that we had with lineup sorting, hovering, and some configuration.
I made the sorting much more robust, while not fully refactoring the code. Lineup now tracks a `permutingMatrix`, which stores lineup's current difference in sort order from the matrix. We need to track this, because when lineup loads with a specific order and is sorted, we need to track the delta. When the matrix is sorted, we can just replace the lineup data so it stays in sync. This approach is much more successful than my previous attempts.
When I added this `permutingMatrix`, it broke the hovering. As a fix, I use the `permutingMatrix` as the map for which nodes are hovered. 
There was also an old function in the lineup …
> Make matrix and lineup stay in sync when sorting and fix additional sorting related bugs

- src/components/ConnectivityQuery.vue
No
Found here and potentially before: https://github.com/multinet-app/multimatrix/pull/409#pullrequestreview-1034719675
Removes the cycles from the connectivity query. This should stop the start and end node being the same in multi hops. I have removed all 2 hop and 3 hop cycles. These are the only ones that can be present with our current number of hops (max = 3).
I also fixed an issue with the node/edge attribute selection in the query. Previously we would select `n1.attribute`, but for some variable names that causes problems. I've updated it so we select ```n1.`attribute` ```
Changes are in the query so will change query results, but there are no UI changes.
TODOs:
> Remove cycles from connectivity queries

- src/components/ControlPanel.vue
- src/components/LineUp.vue
- src/components/MultiMatrix.vue
- src/store/index.ts
- src/types.ts
Closes #314
Closes #399
Closes #402 
Closes #404 
This PR fixes a small issue with the legend count after aggregating, allows aggregating from lineup, and fixes aggregated neighbor highlighting.
The issue with legend counts was an easy fix that just required cloning the network as it was saved on load and read again to aggregate and reset the network.
To allow aggregation from lineup, we watch for that event and trigger a global aggregation, which clears out the lineup and matrix and loads the new network.
To fix the neighbor highlight, I was going to do something complicated with searching through children, etc., but we just need to recompute neighbors when the network expands/retracts. Since the edges are correct, that fixes things up.
There are no real UI changes. The …
> Fix some aggregated network bugs

- src/components/ConnectivityQuery.vue
Closes #350 
This PR makes the connectivity query use `v-autocompletes` for `!=` operators.
No
> Use autocompletes for != in connectivity query

- src/components/MultiMatrix.vue
- src/store/index.ts
Depends on #420 
Closes #190 
This enables nested sorting in the matrix. We sort by sorting all nodes to where they would like to be (sometimes with children separated from their parents), then moving the children to be under their parents in the same order that they would like to be in. This ensures that the sorting is nested.
I also cleaned up some of the original sorting code, since it was a bit of a mess.
Finally, I updated the aggregation, expanding, and contracting logic so that all permuations of edges are added to the network: `child - child`, `child - supernode`, `supernode - child`, and `supernode - supernode`. I added a filter to the code that finds the fill level for each cell so that only the edges that make sense are used in the calculations. This means that the supernodes …
> Nested sorting

- package.json
- src/App.vue
- src/components/AlertBanner.vue
- src/components/ConnectivityQuery.vue
- src/components/ContextMenu.vue
- src/components/ControlPanel.vue
- src/components/EdgeSlices.vue
- src/components/EdgeSlicing.vue
- src/components/IntermediaryNodes.vue
- src/components/LineUp.vue
- src/components/MultiMatrix.vue
- src/components/PathTable.vue
- src/components/ProvVis.vue
- src/main.ts
- src/store/index.ts
- src/types.ts
- yarn.lock
Closes #
This vastly simplifies the store object that we have to maintain. We've gone from requiring mutations, to not, and we now have a path forward on the vue 3 sanctioned store library. While this change wasn't strictly necessary for that change, we're now not using direct-vuex, and we no longer need to use computed get/set logic to update. That is a huge simplification.
The only remaining changes to get us fully up to date with vue 3 will be migrating to it, and using vuetify 3. Vuetify is still in beta, and not well documented at the moment. I think it would be prescient to wait a little while longer for that migration.
I removed some javascript Set logic here, since vue 2 doesn't deal with the reactivity of Sets. We can plan to add that back when we're using vue 3, since they are …
> Migrate from vuex to pinia

- src/components/EdgeSlices.vue
- src/components/EdgeSlicing.vue
- src/store/index.ts
- src/store/provenance.ts
- src/types.ts
Closes #448  
This PR makes the edge slicer work with the new store design. The goal is to have the provenance store able to rehydrate the application, thus we need to store the slicing state in trrack.
N/A
TODOs:
> Make edge slicing work with the trrack store

- package.json
- src/components/ColorScaleLegend.vue
- src/components/ControlPanel.vue
- yarn.lock
Closes #441 
This refactor the color scale legend code to use a custom component, instead of relying on the defunct and unmaintained d3-svg-legend library.
Edge Legend:
Int Node Table:
No
> Drop d3-svg-legend, add custom component ColorScaleLegend

- src/components/ContextMenu.vue
- src/components/ControlPanel.vue
- src/components/LineUp.vue
- src/components/MultiMatrix.vue
- src/lib/provenanceUtils.ts
- src/store/index.ts
- src/store/provenance.ts
- src/types.ts
Closes #440
Closes #444 
Closes #445 
This fixes the matrix sorting and adds the sorting variable to the provenance store.
Nested sorting (alphabetical):
Network Sorting (clusters):
Neighbor Sorting after alphabetical sorting:
TODOs:
> Fix matrix sorting and add it to trrack provenance

- package.json
- src/App.vue
- src/store/provenance.ts
- yarn.lock
No
There was a bug that allowed us to save the session as a string in the multinet db. This PR fixes that issue and adds an enhancement from the trrack library that allows us to import and export the provenance as an object. This simplifies some code and means we don't need to JSON dump and stringily as the states move through the multinet ecosystem.
N/A
TODOs:
> Use number for sessionId and handle states that are objects (not string)

- src/App.vue
- src/store/index.ts
Closes #439
This address both issues mentioned in #439: 1) a human readable label by default, and 2). a search box that works for any node variable.
I've propagated the search box fix to multilink as well.
No
> Add logic to set a default label (if defined on upload), make search box work for any node variable

- .eslintrc.js
- src/components/ContextMenu.vue
- src/components/ControlPanel.vue
- src/components/LineUp.vue
- src/lib/provenanceUtils.ts
- src/store/index.ts
- src/store/provenance.ts
- src/types.ts
Closes #443
Closes #462
This PR fixes a few bugs with lineup and adds the ability to make the matrix cells smaller.
For the matrix cells, I just had to increase the size of the range that I could use for the cells. There was also a bug where the lineup font size was not updating with the cell size correctly that I addressed.
In lineup, I changed the sort logic to allow lineup to sort the matrix and I'm currently working on opposite direction. There were also some bugs that led to the matrix re-rendering constantly that are addressed as a part of this fix. Somehow, the sort order was being changed which would trigger lineup to update the data and then re-render. Quite a mess.
N/A
TODOs:
> Allow setting cell size smaller and fix lineup infinite re-render bug and sort logic
